In [1]:
import numpy as np,pandas as pd

In [2]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 

In [3]:
a=pd.Series({'a':12,'b':42,'c':535,'d':55},dtype=np.int32)

In [4]:
a

a     12
b     42
c    535
d     55
dtype: int32

In [5]:
a=pd.Series({'a':12,'b':42,'c':535,'d':55},name='Series1')

In [6]:
a

a     12
b     42
c    535
d     55
Name: Series1, dtype: int64

In [7]:
data={'name':'chaitanya','age':21,'number':9325942528}

In [8]:
pd.Series(data,name='DictSeries')

name       chaitanya
age               21
number    9325942528
Name: DictSeries, dtype: object

In [12]:
ser=pd.Series([11,22,33,44,55,66],index=['A','B','C','D','E','F'],dtype=('i4'))

In [13]:
ser

A    11
B    22
C    33
D    44
E    55
F    66
dtype: int32

In [18]:
ser.values

array([11, 22, 33, 44, 55, 66], dtype=int32)

In [19]:
ser.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [20]:
ser.name='Series_11'

In [21]:
ser

A    11
B    22
C    33
D    44
E    55
F    66
Name: Series_11, dtype: int32

In [26]:
ser.rename('series11')

A    11
B    22
C    33
D    44
E    55
F    66
Name: series11, dtype: int32

In [27]:
ser

A    11
B    22
C    33
D    44
E    55
F    66
Name: Series_11, dtype: int32

In [31]:
ser['A']

11

In [32]:
ser[0]

11

In [33]:
ser[:-1]

A    11
B    22
C    33
D    44
E    55
Name: Series_11, dtype: int32

In [34]:
ser[:3]

A    11
B    22
C    33
Name: Series_11, dtype: int32

In [35]:
ser[-3:-1]

D    44
E    55
Name: Series_11, dtype: int32

In [36]:
ser[-3:]

D    44
E    55
F    66
Name: Series_11, dtype: int32

In [88]:
ser[-1]=123

In [89]:
ser[['A','C','F']]

A     11
C     33
F    123
Name: Series_11, dtype: int64

In [40]:
ser

A     11
B     22
C     33
D     44
E     55
F    123
Name: Series_11, dtype: int32

In [41]:
ser[-2:]=[555,666]

In [42]:
ser

A     11
B     22
C     33
D     44
E    555
F    666
Name: Series_11, dtype: int64

In [48]:
np_ser=pd.Series(np.linspace(10,20,7,endpoint=False,dtype=('i2')))

In [54]:
np_ser[-2]=18
np_ser

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [52]:
np_ser.describe()

count     7.000000
mean     13.857143
std       3.023716
min      10.000000
25%      11.500000
50%      14.000000
75%      16.000000
max      18.000000
dtype: float64

In [55]:
np_ser.value_counts()

18    2
10    1
11    1
12    1
14    1
15    1
17    1
dtype: int64

In [56]:
np_ser.isin([11,111])

 0    False
 1     True
 2    False
 3    False
 4    False
 5    False
 6    False
-2    False
dtype: bool

In [59]:
np_ser.isnull()

 0    False
 1    False
 2    False
 3    False
 4    False
 5    False
 6    False
-2    False
dtype: bool

In [60]:
np_ser.notnull()

 0    True
 1    True
 2    True
 3    True
 4    True
 5    True
 6    True
-2    True
dtype: bool

In [65]:
np_ser[np_ser.isin([11,111,17])]

1    11
5    17
dtype: int64

In [66]:
ser1=np_ser.copy()

In [67]:
del np_ser

In [69]:
ser1

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [77]:
ser2=pd.Series(np.linspace(12,21,8,dtype='i8'),name='ser2')

In [78]:
ser2

0    12
1    13
2    14
3    15
4    17
5    18
6    19
7    21
Name: ser2, dtype: int64

In [79]:
ser1+ser2

-2     NaN
 0    22.0
 1    24.0
 2    26.0
 3    29.0
 4    32.0
 5    35.0
 6    37.0
 7     NaN
dtype: float64

In [80]:
ser1*2

 0    20
 1    22
 2    24
 3    28
 4    30
 5    34
 6    36
-2    36
dtype: int64

In [81]:
ser1//2

 0    5
 1    5
 2    6
 3    7
 4    7
 5    8
 6    9
-2    9
dtype: int64

In [83]:
np.remainder(ser1,np.array([2]))

 0    0
 1    1
 2    0
 3    0
 4    1
 5    1
 6    0
-2    0
dtype: int64

In [84]:
ser1

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [85]:
np.unique(ser1)

array([10, 11, 12, 14, 15, 17, 18])

In [86]:
ser1.unique()

array([10, 11, 12, 14, 15, 17, 18])

In [91]:
ser1.is_unique

False

In [92]:
ser1.shape

(8,)

In [93]:
ser1.size

8

In [94]:
ser1.ndim

1

In [96]:
ser1.head(2)

0    10
1    11
dtype: int64

In [97]:
ser1.tail(2)

 6    18
-2    18
dtype: int64

In [98]:
ser1.mean()

14.375

In [99]:
ser1.min()

10

In [100]:
ser1.max()


18

In [101]:
ser1.std()

3.1594529363709247

In [102]:
ser1.var()

9.982142857142858

In [104]:
ser1.count()

8

In [105]:
ser1.product()

1526817600

In [107]:
np.modf(ser1)

( 0    0.0
  1    0.0
  2    0.0
  3    0.0
  4    0.0
  5    0.0
  6    0.0
 -2    0.0
 dtype: float64,
  0    10.0
  1    11.0
  2    12.0
  3    14.0
  4    15.0
  5    17.0
  6    18.0
 -2    18.0
 dtype: float64)

In [109]:
ser1.nunique()
# how values are unique

7

In [110]:
ser1

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [111]:
ser1.sort_values()

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [112]:
ser1.sort_values(ascending=False)

 6    18
-2    18
 5    17
 4    15
 3    14
 2    12
 1    11
 0    10
dtype: int64

In [113]:
ser1.sort_index()

-2    18
 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
dtype: int64

In [137]:
ser=pd.Series([53,34,234,np.nan,53,np.nan])

In [115]:
ser

0     53.0
1     34.0
2    234.0
3      NaN
4     53.0
5      NaN
dtype: float64

In [116]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [117]:
ser.notnull()

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool

In [118]:
ser.isna()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [119]:
ser.isna().sum()

2

In [123]:
ser.count()
# return number of not null values

4

In [124]:
ser.size

6

In [125]:
ser.nlargest()

2    234.0
0     53.0
4     53.0
1     34.0
dtype: float64

In [126]:
ser.nlargest(1)

2    234.0
dtype: float64

In [127]:
ser.max()

234.0

In [128]:
ser.nsmallest(2)

1    34.0
0    53.0
dtype: float64

In [129]:
ser.min()

34.0

In [138]:
ser.le(35,fill_value=40)

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [139]:

ser

0     53.0
1     34.0
2    234.0
3      NaN
4     53.0
5      NaN
dtype: float64

In [140]:
ser[ser<40]

1    34.0
dtype: float64

In [141]:
ser<40

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [145]:
ser!=34

0     True
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [146]:
dir(ser)
# it will gives all methods which we can use with series

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__r

In [148]:
ser._values

array([ 53.,  34., 234.,  nan,  53.,  nan])

In [149]:
ser.values

array([ 53.,  34., 234.,  nan,  53.,  nan])

In [150]:
ser.abs()

0     53.0
1     34.0
2    234.0
3      NaN
4     53.0
5      NaN
dtype: float64

In [151]:
ser.argmax()
# index position of largest values in series

2

In [152]:
ser.argmin()

1

In [153]:
ser.nlargest(1)
# compare argmax with nlargest and argmin with nsmallest

2    234.0
dtype: float64

In [160]:
ser=pd.Series(np.arange(5,15,3),dtype=float)

In [161]:
ser

0     5.0
1     8.0
2    11.0
3    14.0
dtype: float64

In [162]:
ser.astype('int32')

0     5
1     8
2    11
3    14
dtype: int32

In [164]:
ser.cummax(skipna=False)

0     5.0
1     8.0
2    11.0
3    14.0
dtype: float64

In [166]:
ser.cummin()

0    5.0
1    5.0
2    5.0
3    5.0
dtype: float64

In [167]:
ser.cumprod()

0       5.0
1      40.0
2     440.0
3    6160.0
dtype: float64

In [168]:
ser.cumsum()

0     5.0
1    13.0
2    24.0
3    38.0
dtype: float64

In [169]:
ser.describe()

count     4.000000
mean      9.500000
std       3.872983
min       5.000000
25%       7.250000
50%       9.500000
75%      11.750000
max      14.000000
dtype: float64

In [172]:
ser.div(ser2)

0    0.416667
1    0.615385
2    0.785714
3    0.933333
4         NaN
5         NaN
6         NaN
7         NaN
dtype: float64

In [173]:
ser2

0    12
1    13
2    14
3    15
4    17
5    18
6    19
7    21
Name: ser2, dtype: int64

In [174]:
ser1

 0    10
 1    11
 2    12
 3    14
 4    15
 5    17
 6    18
-2    18
dtype: int64

In [176]:
ser=pd.Series([42,43,np.nan,np.nan,43,np.nan])

In [177]:
ser

0    42.0
1    43.0
2     NaN
3     NaN
4    43.0
5     NaN
dtype: float64

In [178]:
ser.dropna()

0    42.0
1    43.0
4    43.0
dtype: float64

In [179]:
ser3=ser.copy()

In [180]:
ser3

0    42.0
1    43.0
2     NaN
3     NaN
4    43.0
5     NaN
dtype: float64

In [183]:
ser3.drop(0,inplace=True)

In [184]:
ser3

1    43.0
2     NaN
3     NaN
4    43.0
5     NaN
dtype: float64

In [185]:
ser3.drop(labels=[1,3,2])

4    43.0
5     NaN
dtype: float64

In [186]:
ser3.dropna()

1    43.0
4    43.0
dtype: float64

In [187]:
ser3.bfill()

1    43.0
2    43.0
3    43.0
4    43.0
5     NaN
dtype: float64

In [188]:
ser3.ffill()

1    43.0
2    43.0
3    43.0
4    43.0
5    43.0
dtype: float64

In [191]:
ser3.fillna(method='ffill')

1    43.0
2    43.0
3    43.0
4    43.0
5    43.0
dtype: float64

In [193]:
ser3=pd.Series([3,4,np.nan,np.nan,np.nan,43])

In [194]:
ser3

0     3.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [201]:
mean=np.mean(ser3)

In [202]:
mean

16.666666666666668

In [203]:
ser3.fillna(mean)

0     3.000000
1     4.000000
2    16.666667
3    16.666667
4    16.666667
5    43.000000
dtype: float64

In [205]:
ser3.fillna(mean).astype(int)

0     3
1     4
2    16
3    16
4    16
5    43
dtype: int64

In [206]:
dir(ser3)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__r

In [207]:
ser3

0     3.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [208]:
ser.median()

43.0

In [209]:
ser3.mode()

0     3.0
1     4.0
2    43.0
dtype: float64

In [210]:
ser.repeat(3)

0    42.0
0    42.0
0    42.0
1    43.0
1    43.0
1    43.0
2     NaN
2     NaN
2     NaN
3     NaN
3     NaN
3     NaN
4    43.0
4    43.0
4    43.0
5     NaN
5     NaN
5     NaN
dtype: float64

In [213]:
ser.repeat([1,2,1,2,1,2])

0    42.0
1    43.0
1    43.0
2     NaN
3     NaN
3     NaN
4    43.0
5     NaN
5     NaN
dtype: float64

In [218]:
ser3

0     3.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [217]:
ser3.transpose()

0     3.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [226]:
ser3.where(ser3<1,12)

0    12.0
1    12.0
2    12.0
3    12.0
4    12.0
5    12.0
dtype: float64

In [227]:
ser3

0     3.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [228]:
ser3.mask(ser3<4,4)
# i prefer this than where

0     4.0
1     4.0
2     NaN
3     NaN
4     NaN
5    43.0
dtype: float64

In [229]:
ser3.where(ser3<4,4)

0    3.0
1    4.0
2    4.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [231]:
ser3.where(ser>4,5)

0    3.0
1    4.0
2    5.0
3    5.0
4    NaN
5    5.0
dtype: float64

In [236]:
ser3.between(1,5)

0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [239]:
ser3.between(40,43,inclusive='left')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool